apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t951hqqlp-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:a40f4065ff0e825d9fbd7e3b4ea9f9c41c2dad1c@sha256:68d082a8867a72aa362934a0f9e9780b57741d200a5716ee0d2f213570ace1de
          name: container-image
